name: Continuous Integratino and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: Windows
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: Setup .Net 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet build
